/-
Copyright (c) 2026 Damiano Testa. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Damiano Testa
-/
import Lean
import ImportGraph.Imports.ImportGraph
import ImportGraph.Graph.TransitiveClosure

/-!
# Dump "reasonable" declarations and/or transitive-import counts

## Outputs

* `--out FILE`: writes one "reasonable" declaration name per line,
  sorted by name. "Reasonable" = not `private`, not `unsafe`, and not
  flagged by `Lean.Name.isInternalDetail`. Autogenerated outputs from
  `to_additive` / `to_dual` / `to_op` are included.

* `--imports-out FILE`: writes a single-line JSON object mapping each
  root-prefixed module to the size of its transitive closure in
  `Lean.Environment.importGraph`.

The flags can be combined; both files are produced from one env load.
If neither is given, defaults to `--out reasonable_decls.txt`.

## Roots

Positional `ROOT` arguments are Lean module names (e.g. `Mathlib`,
`Plausible`). Each is imported and used as a `Name`-prefix filter on
both outputs. Default: `Mathlib`.

## Usage

```
lake env lean --run scripts/pr_summary/dumpReasonableDecls.lean \
    [-o DECLS_OUT | --out DECLS_OUT] \
    [--imports-out IMPORTS_OUT] \
    [ROOT ...]
```

## Dependencies

`Lean` and the `importGraph` package. Runs in any Lake project whose
`LEAN_PATH` (via `lake env`) sees the requested roots.
-/

open Lean

/-- Command-line configuration. -/
structure Config where
  /-- Path for the declarations dump; `none` means "don't dump declarations". -/
  declsOut   : Option System.FilePath := none
  /-- Path for the transitive-import counts JSON; `none` means "don't dump imports". -/
  importsOut : Option System.FilePath := none
  /-- Module roots to import (via `withImportModules`) and use as a
  `Name`-prefix filter on both outputs. Empty disables the filter. -/
  roots      : Array Name := #[]
  deriving Inhabited

def helpText : String :=
"Dump declarations + transitive imports from a Lean environment.

Usage:
  lake env lean --run dumpReasonableDecls.lean [OPTIONS] [ROOT ...]

Outputs (any combination; both can run in one env load):
  -o, --out FILE        write 'reasonable' declaration names (one per line)
      --imports-out F   write transitive-import counts as JSON
                        (object keyed by module name)

If no output flag is given, defaults to `-o reasonable_decls.txt`.

Each ROOT (e.g. Mathlib) is imported, and both outputs are filtered to
modules under the root prefix. Default: Mathlib.

Options:
  -o, --out FILE        decls output file
      --imports-out F   transitive-imports JSON file
  -h, --help            show this message and exit
"

/-- Parse a `--out=`-style argument. Returns the embedded path if matched. -/
def parseOutEq? (arg : String) : Option String :=
  if arg.startsWith "--out=" then some (arg.drop "--out=".length).toString
  else if arg.startsWith "-o=" then some (arg.drop "-o=".length).toString
  else none

partial def parseArgs : List String → Config → IO Config
  | [],                                  cfg => pure cfg
  | (("-h" | "--help") :: _),            _   => do IO.println helpText; IO.Process.exit 0
  | ("-o" :: f :: rest),                 cfg => parseArgs rest { cfg with declsOut := some f }
  | ("--out" :: f :: rest),              cfg => parseArgs rest { cfg with declsOut := some f }
  | ("--imports-out" :: f :: rest),      cfg => parseArgs rest { cfg with importsOut := some f }
  | ("--imports-out" :: _),              _   =>
      throw <| IO.userError "--imports-out requires a file argument"
  | (a :: rest),                         cfg =>
    if let some f := parseOutEq? a then
      parseArgs rest { cfg with declsOut := some f }
    else if a.startsWith "--imports-out=" then
      parseArgs rest { cfg with importsOut := some (a.drop "--imports-out=".length).toString }
    else if a.startsWith "-" then
      throw <| IO.userError s!"unknown option: {a}\n\n{helpText}"
    else
      parseArgs rest { cfg with roots := cfg.roots.push a.toName }

/-- A constant is "reasonable" iff it is not `private`, not `unsafe`, and not
flagged as an internal detail (`Lean.Name.isInternalDetail`). -/
def isReasonable (n : Name) (ci : ConstantInfo) : Bool :=
  !n.isInternalDetail && !isPrivateName n && !ci.isUnsafe

/-- The `Name` of the module in which `n` is defined, or `none` if `n` has no
source module (e.g. it was synthesised in the current "input" module). -/
def sourceModule? (env : Environment) (n : Name) : Option Name := do
  let idx ← env.getModuleIdxFor? n
  env.allImportedModuleNames[idx.toNat]?

/-- True iff `n`'s source module is `prefix.<...>` for some `prefix` in `roots`.
An empty `roots` accepts everything. -/
def inAnyRoot (env : Environment) (roots : Array Name) (n : Name) : Bool :=
  if roots.isEmpty then true
  else match sourceModule? env n with
    | none   => false
    | some m => roots.any fun p => p.isPrefixOf m

/-- Iterate the constants once and write the reasonable-declaration dump. -/
private def writeDeclsDump (env : Environment) (roots : Array Name)
    (outFile : System.FilePath) : IO Nat := do
  let decls : Array Name :=
    env.constants.fold (init := #[]) fun acc n ci =>
      if isReasonable n ci && inAnyRoot env roots n then acc.push n
      else acc
  let sorted := decls.qsort (fun a b => a.toString < b.toString)
  IO.FS.withFile outFile .write fun h => do
    for n in sorted do h.putStrLn n.toString
  return sorted.size

/-- Write the transitive-import counts JSON. Keys are strict descendants of
any configured root; non-root boundary leaves are dropped from the key set.
Output format matches `count-trans-deps.py`. -/
private def writeImportsDump (env : Environment) (roots : Array Name)
    (outFile : System.FilePath) : IO Nat := do
  let fullGraph := env.importGraph
  -- Drop edges whose source is NOT under any configured root. Non-root
  -- targets survive only as leaves — they have no outgoing edges in the
  -- restricted graph, so they get counted once as a direct import of any
  -- root module that mentions them, but the search does not descend.
  let restricted : NameMap (Array Name) :=
    fullGraph.foldl (init := ({} : NameMap (Array Name))) fun acc src deps =>
      if roots.any (·.isPrefixOf src) then acc.insert src deps
      else acc
  let closure := Lean.NameMap.transitiveClosure restricted
  -- Restrict to strict descendants of a root (drops the root itself and
  -- any non-root keys that snuck in). Sort by key for deterministic bytes.
  let pairs : Array (String × Json) :=
    closure.foldl (init := #[]) fun acc n s =>
      if roots.any (fun p => p != n && p.isPrefixOf n) then
        acc.push (n.toString, Json.num s.size)
      else acc
  let sorted := pairs.qsort (fun a b => a.1 < b.1)
  let json := Json.mkObj sorted.toList
  IO.FS.writeFile outFile json.compress
  return sorted.size

unsafe def runDump (cfg : Config) : IO UInt32 := do
  Lean.initSearchPath (← Lean.findSysroot)
  Lean.enableInitializersExecution
  let imports : Array Import := cfg.roots.map ({ module := · })
  Lean.withImportModules imports {} (trustLevel := 1024) fun env => do
    let rootsStr := " ".intercalate (cfg.roots.toList.map toString)
    if let some path := cfg.declsOut then
      let n ← writeDeclsDump env cfg.roots path
      IO.println s!"Wrote {n} reasonable declarations from [{rootsStr}] to {path}"
    if let some path := cfg.importsOut then
      let n ← writeImportsDump env cfg.roots path
      IO.println s!"Wrote {n} transitive-import counts from [{rootsStr}] to {path}"
    return 0

def main (args : List String) : IO UInt32 := do
  let mut cfg ← parseArgs args {}
  if cfg.roots.isEmpty then cfg := { cfg with roots := #[`Mathlib] }
  if cfg.declsOut.isNone && cfg.importsOut.isNone then
    cfg := { cfg with declsOut := some "reasonable_decls.txt" }
  unsafe runDump cfg
