#!/usr/bin/env bash
# Generate PR Summary Comment
# Reads JSON output from verify_commits.sh and generates a markdown comment.
#
# Usage: ./verify_commits.sh <base_ref> --json | ./verify_commits_summary.sh <repo> <pr_number>
#
# Failed commits get a collapsible `<details>` block containing the actual
# error output. The renderer dispatches on `failure_kind` (no keyword
# matching of error messages — the underlying tool's error message is the
# diagnosis). A soft cap on total comment size is applied: if rendered
# output would exceed MAX_COMMENT_BYTES (default 50000), output excerpts are
# dropped from later failed commits, replaced by a "see CI logs" pointer.

set -euo pipefail

REPO="${1:-}"
PR_NUMBER="${2:-}"
MAX_COMMENT_BYTES="${MAX_COMMENT_BYTES:-50000}"

if [[ -z "$REPO" || -z "$PR_NUMBER" ]]; then
  echo "Usage: $0 <repo> <pr_number>" >&2
  echo "  Reads JSON from stdin" >&2
  exit 2
fi

JSON=$(cat)

# Validate the JSON. If it doesn't parse, emit a fallback comment so the
# author still gets *some* feedback rather than a silently-empty comment.
if ! echo "$JSON" | jq -e . >/dev/null 2>&1; then
  cat <<EOF
## Commit Verification Summary

> [!WARNING]
> The commit verification job emitted output that could not be parsed.
> Please check the [CI logs](https://github.com/$REPO/pull/$PR_NUMBER/checks) and ping a maintainer if this persists.

---
*Generated by commit verification CI*
EOF
  exit 0
fi

SUCCESS=$(echo "$JSON" | jq -r '.success')
TRANSIENT_VERIFIED=$(echo "$JSON" | jq -r '.transient_verified')
SUBSTANTIVE_COUNT=$(echo "$JSON" | jq '.substantive_commits | length')
AUTO_COUNT=$(echo "$JSON" | jq '.auto_commits | length')
AUTO_VERIFIED_COUNT=$(echo "$JSON" | jq '[.auto_commits[] | select(.verified == true)] | length')
TRANSIENT_COUNT=$(echo "$JSON" | jq '.transient_commits | length')

OUT=$(mktemp)
trap 'rm -f "$OUT"' EXIT

emit()     { printf '%s\n' "$@" >> "$OUT"; }
emit_raw() { printf '%s' "$1" >> "$OUT"; }

emit "## Commit Verification Summary"
emit ""

if [[ "$SUCCESS" == "true" ]]; then
  emit "All verifications passed."
  emit ""
else
  emit "> [!WARNING]"
  emit "> Some verifications failed. See details below."
  emit ""
fi

# --- Substantive commits ---
if [[ "$SUBSTANTIVE_COUNT" -gt 0 ]]; then
  emit "### Commits to Review ($SUBSTANTIVE_COUNT)"
  emit ""
  while IFS= read -r line; do emit "$line"; done < <(
    echo "$JSON" | jq -r '.substantive_commits[] | "- `\(.short)`: \(.subject)"'
  )
  emit ""
  emit "[View PR diff](https://github.com/$REPO/pull/$PR_NUMBER/files)"
  emit ""
else
  emit "### Commits to Review"
  emit ""
  emit "No substantive commits — this PR consists entirely of automated and/or transient commits."
  emit ""
fi

# Render one failed-auto-commit details block.
# Args: short, command, failure_kind, exit_code, timeout_seconds,
#       output_excerpt, output_truncated, diff_excerpt, diff_truncated,
#       include_excerpts (true/false)
render_failed_auto() {
  local short="$1" subject="$2" failure_kind="$3"
  local exit_code="$4" timeout_seconds="$5"
  local output_excerpt="$6" output_truncated="$7"
  local diff_excerpt="$8" diff_truncated="$9"
  local include_excerpts="${10}"

  emit "<details>"
  # Replace any backticks in the subject so the surrounding code span renders cleanly.
  local safe_subject=${subject//\`/\\\`}
  emit "<summary>❌ <code>$short</code>: <code>${safe_subject}</code></summary>"
  emit ""
  case "$failure_kind" in
    timed_out)      emit "Command timed out after ${timeout_seconds}s." ;;
    command_failed) emit "Command exited with code $exit_code." ;;
    tree_mismatch)  emit "Command succeeded but produced a different tree than the commit." ;;
    *)              emit "Verification failed (kind: $failure_kind)." ;;
  esac
  emit ""

  if [[ "$include_excerpts" == "true" ]]; then
    if [[ -n "$output_excerpt" ]]; then
      emit "**Output:**"
      emit ""
      emit '```'
      emit_raw "$output_excerpt"
      emit ""
      emit '```'
      [[ "$output_truncated" == "true" ]] && emit "_(output truncated; see CI logs for the full output)_"
      emit ""
    fi
    if [[ "$failure_kind" == "tree_mismatch" && -n "$diff_excerpt" ]]; then
      emit "**Difference from committed tree:**"
      emit ""
      emit '```'
      emit_raw "$diff_excerpt"
      emit ""
      emit '```'
      [[ "$diff_truncated" == "true" ]] && emit "_(diff truncated; see CI logs for the full diff)_"
      emit ""
    fi
  else
    emit "_(excerpts omitted to keep comment under size limit; see [CI logs](https://github.com/$REPO/pull/$PR_NUMBER/checks))_"
    emit ""
  fi
  emit "</details>"
  emit ""
}

# --- Automated commits ---
if [[ "$AUTO_COUNT" -gt 0 ]]; then
  if [[ "$AUTO_VERIFIED_COUNT" -eq "$AUTO_COUNT" ]]; then
    AUTO_STATUS_ICON="✅"
    AUTO_STATUS_TEXT="all verified"
  else
    AUTO_STATUS_ICON="❌"
    AUTO_STATUS_TEXT="$AUTO_VERIFIED_COUNT/$AUTO_COUNT verified"
  fi
  emit "### $AUTO_STATUS_ICON Automated commits ($AUTO_COUNT) — $AUTO_STATUS_TEXT"
  emit ""

  # Verified commits: one-liner each.
  while IFS= read -r line; do emit "$line"; done < <(
    echo "$JSON" | jq -r '.auto_commits[] | select(.verified == true) | "- ✅ `\(.short)`: `\(.subject)`"'
  )

  # Failed commits: per-commit details. Apply the soft size cap as we go.
  if [[ "$AUTO_VERIFIED_COUNT" -lt "$AUTO_COUNT" ]]; then
    emit ""
    while IFS= read -r failed; do
      f_short=$(echo "$failed"   | jq -r '.short')
      f_subject=$(echo "$failed" | jq -r '.subject')
      f_kind=$(echo "$failed"    | jq -r '.failure_kind // ""')
      f_exit=$(echo "$failed"    | jq -r '.exit_code // ""')
      f_timeout=$(echo "$failed" | jq -r '.timeout_seconds // ""')
      f_out=$(echo "$failed"     | jq -r '.output_excerpt // ""')
      f_out_t=$(echo "$failed"   | jq -r '.output_truncated // false')
      f_diff=$(echo "$failed"    | jq -r '.diff_excerpt // ""')
      f_diff_t=$(echo "$failed"  | jq -r '.diff_truncated // false')

      current_size=$(wc -c < "$OUT" | tr -d ' ')
      include_excerpts=true
      if [[ $current_size -gt $((MAX_COMMENT_BYTES - 4096)) ]]; then
        include_excerpts=false
      fi
      render_failed_auto \
        "$f_short" "$f_subject" "$f_kind" \
        "$f_exit" "$f_timeout" \
        "$f_out" "$f_out_t" \
        "$f_diff" "$f_diff_t" \
        "$include_excerpts"
    done < <(echo "$JSON" | jq -c '.auto_commits[] | select(.verified == false)')
  fi
fi

# --- Transient commits ---
if [[ "$TRANSIENT_COUNT" -gt 0 ]]; then
  if [[ "$TRANSIENT_VERIFIED" == "true" ]]; then
    T_ICON="✅"
    T_TEXT="net effect: none"
  else
    T_ICON="❌"
    T_KIND=$(echo "$JSON" | jq -r '.transient_failure_kind // ""')
    case "$T_KIND" in
      cherry_pick_conflict) T_TEXT="cherry-pick conflict during replay" ;;
      tree_mismatch)        T_TEXT="net effect is non-empty" ;;
      *)                    T_TEXT="verification failed" ;;
    esac
  fi
  emit "### $T_ICON Transient commits ($TRANSIENT_COUNT) — $T_TEXT"
  emit ""
  while IFS= read -r line; do emit "$line"; done < <(
    echo "$JSON" | jq -r '.transient_commits[] | "- `\(.short)`: \(.subject)"'
  )
  emit ""

  if [[ "$TRANSIENT_VERIFIED" != "true" ]]; then
    case "$T_KIND" in
      cherry_pick_conflict)
        T_FAILED_SHORT=$(echo "$JSON"   | jq -r '.transient_failed_short // ""')
        T_FAILED_SUBJECT=$(echo "$JSON" | jq -r '.transient_failed_subject // ""')
        T_OUT=$(echo "$JSON"            | jq -r '.transient_output_excerpt // ""')
        T_OUT_T=$(echo "$JSON"          | jq -r '.transient_output_truncated // false')
        emit "<details>"
        emit "<summary>Conflict on <code>$T_FAILED_SHORT</code>: $T_FAILED_SUBJECT</summary>"
        emit ""
        if [[ -n "$T_OUT" ]]; then
          emit "**Output:**"
          emit ""
          emit '```'
          emit_raw "$T_OUT"
          emit ""
          emit '```'
          [[ "$T_OUT_T" == "true" ]] && emit "_(output truncated; see CI logs for the full output)_"
          emit ""
        fi
        emit "</details>"
        emit ""
        ;;
      tree_mismatch)
        T_DIFF=$(echo "$JSON"   | jq -r '.transient_diff_excerpt // ""')
        T_DIFF_T=$(echo "$JSON" | jq -r '.transient_diff_truncated // false')
        emit "<details>"
        emit "<summary>Difference between final tree and replay-without-transients</summary>"
        emit ""
        if [[ -n "$T_DIFF" ]]; then
          emit '```'
          emit_raw "$T_DIFF"
          emit ""
          emit '```'
          [[ "$T_DIFF_T" == "true" ]] && emit "_(diff truncated; see CI logs for the full diff)_"
          emit ""
        fi
        emit "</details>"
        emit ""
        ;;
    esac
  fi
fi

emit "---"
emit "*Generated by commit verification CI*"

# Hard cap: if we still exceed MAX_COMMENT_BYTES, truncate.
final_size=$(wc -c < "$OUT" | tr -d ' ')
if [[ $final_size -gt $MAX_COMMENT_BYTES ]]; then
  head -c $((MAX_COMMENT_BYTES - 200)) "$OUT"
  echo ""
  echo ""
  echo "_(comment truncated; full report in [CI logs](https://github.com/$REPO/pull/$PR_NUMBER/checks))_"
else
  cat "$OUT"
fi
